[project]
name = "soundtext4agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SamYuan1990", email = "yy19902439@126.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.6",
    "onnxruntime==1.23.2",
    "pypinyin>=0.55.0",
    "sentencepiece>=0.2.1",
    "sherpa-onnx==1.12.28",
    "sounddevice>=0.5.5",
    "soundfile>=0.13.1",
]

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"
